### ISSUE TITLE
KeyError: 'dragonfly' when importing the huggingface checkpoints

### ISSUE THREAD

**Issue by vjz3qz** [togethercomputer/Dragonfly#10]
I'm looking to import the Dragonfly checkpoints from huggingface, but I keep getting a model config key error. I've ensure that I have read token for huggingface and accepted terms. Let me know if there is a solution to this issue.
<img width="612" alt="Screenshot 2024-06-08 at 10 20 50 AM" src="https://github.com/togethercomputer/Dragonfly/assets/105752868/778f5d2a-61a1-4256-870d-77b82306d896">
<img width="935" alt="Screenshot 2024-06-08 at 10 21 18 AM" src="https://github.com/togethercomputer/Dragonfly/assets/105752868/623727ef-8fce-467f-8c14-55a4b72657d2">
<img width="930" alt="Screenshot 2024-06-08 at 10 21 28 AM" src="https://github.com/togethercomputer/Dragonfly/assets/105752868/d7e3efe7-6515-4367-b7b8-ec50d76771d6">

**Comment by rthapa84** [comment]
Hey, thank you for reaching out. First, please make sure you follow the installation instruction on readme to make sure you install the tight packages. And second, please follow the instruction in this script to load and run our model (https://github.com/togethercomputer/Dragonfly/blob/main/test_dragonfly.py). At the moment, Dragonfly is not integrated fully with Transformer package, and therefore, you cannot load it that way.

**Comment by vjz3qz** [comment]
Thanks for letting me know! That works. Would love to know once Dragonfly is fully integrated with the Transformers package.
